language: java
addons:
  sonarcloud:
    organization: borisv13-github
    
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
- mvn -Ppitest -Dfeatures=+GIT test-compile
