language: java
env:
  global:
    - MOZ_HEADLESS=1
addons:
  firefox: latest
  sonarcloud:
    organization: borisv13-github
    
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
